import { createSlice } from "@reduxjs/toolkit";

const listSlice = createSlice({
    name: "List",
    initialState: {
        list: [
            {
                "type": "anime",
                "title": "Bleach: Thousand-Year Blood War - The Separation",
                "original_title": "BLEACH 千年血戦篇-訣別譚-",
                "description": "Ichigo and the Soul Reapers continue their intense battle against Yhwach and the Quincy invasion as the fate of both worlds hangs in the balance.",
                "genres": ["Action", "Supernatural", "Fantasy"],
                "status": "completed",
                "season": 2,
                "total_seasons": 4,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Pierrot",
                "poster_url": "./Bleach.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Jujutsu Kaisen Season 2",
                "original_title": "呪術廻戦 第2期",
                "description": "Gojo's past unfolds while the Shibuya Incident reveals the true threat of Jujutsu Society as powerful curses wreak havoc on Tokyo.",
                "genres": ["Action", "Dark Fantasy", "Supernatural"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "MAPPA",
                "poster_url": "./JuJutsu_Kaisen.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Classroom of the Elite",
                "original_title": "ようこそ実力至上主義の教室へ",
                "description": "In an elite government school, students compete ruthlessly through exams and psychological games with their futures at stake.",
                "genres": ["Psychological", "Drama", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Lerche",
                "poster_url": "./Classroom_of_the_Elite.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "One Punch Man",
                "original_title": "ワンパンマン",
                "description": "Saitama, an overpowered hero who defeats enemies with a single punch, searches for a worthy opponent to rekindle his passion for battle.",
                "genres": ["Action", "Comedy", "Superhero"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Madhouse",
                "poster_url": "./One_Punch_Man.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Mob Psycho 100 III",
                "original_title": "モブサイコ 100 III",
                "description": "Mob, a middle school psychic, continues to control his overwhelming powers while navigating friendships, school, and personal growth.",
                "genres": ["Action", "Comedy", "Supernatural"],
                "status": "completed",
                "season": 3,
                "total_seasons": 3,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Bones",
                "poster_url": "./Mob_Psycho_100.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Demon Slayer: Kimetsu no Yaiba - Hashira Training Arc",
                "original_title": "鬼滅の刃 柱稽古編",
                "description": "Tanjiro undergoes intense training with the Hashira to prepare for his final confrontation with Muzan Kibutsuji.",
                "genres": ["Action", "Dark Fantasy", "Supernatural"],
                "status": "completed",
                "season": 4,
                "total_seasons": 4,
                "year": 2024,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Ufotable",
                "poster_url": "./Demon-Slayer.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Spy x Family Season 2",
                "original_title": "SPY×FAMILY シーズン2",
                "description": "The Forger family continues their secret missions while maintaining the facade of a perfect family under constant danger and scrutiny.",
                "genres": ["Action", "Comedy", "Slice of Life"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Wit Studio & Cloverworks",
                "poster_url": "./Spy-X-Family.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Death Note",
                "original_title": "デスノート",
                "description": "A student discovers a supernatural notebook that kills anyone whose name is written in it, leading to a battle of wits with a mysterious detective.",
                "genres": ["Psychological", "Thriller", "Supernatural"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2006,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Madhouse",
                "poster_url": "./Death-Note.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Black Clover",
                "original_title": "ブラッククローバー",
                "description": "Aster, a powerless boy in a world of mages, joins the Black Bull squad and strives to become the Wizard King through sheer determination and effort.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 5,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Pierrot",
                "poster_url": "./Black-Clover.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Eminence in Shadow",
                "original_title": "陰の実力者になりたくて",
                "description": "Cid Kagenou, a reborn otaku, manipulates events from the shadows as the mysterious Shadow while building his secret organization.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Nexus",
                "poster_url": "./The-Eminence-in-Shadow.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Reincarnation of the Strongest Exorcist in Another World",
                "original_title": "最強陰陽師の異世界転生記",
                "description": "A powerful exorcist is reincarnated in a fantasy world where he uses his spiritual powers to become the strongest warrior.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "J.C.Staff",
                "poster_url": "./The-Reincarnation-of-the-Strongest-Exorcist-in-Another-World.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Fire Force",
                "original_title": "炎炎ノ消防隊",
                "description": "Shinra Kusakabe joins a special firefighting force to combat spontaneous human combustion while uncovering the truth behind supernatural flames.",
                "genres": ["Action", "Adventure", "Supernatural"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "David Production",
                "poster_url": "./Fire-Force.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Hunter x Hunter",
                "original_title": "ハンターハンター",
                "description": "Gon seeks to become a Hunter like his father, embarking on an epic adventure filled with dangerous challenges, friendships, and dark conspiracies.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2011,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Madhouse",
                "poster_url": "./Hunter-X-Hunter.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "My Teen Romantic Comedy SNAFU",
                "original_title": "やはり俺の青春ラブコメはまちがっている。",
                "description": "An introverted student joins a school club where he and two others solve student problems with unconventional methods and hidden romance.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2013,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Brain's Base",
                "poster_url": "./My-Teen-Romantic-Comedy.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Daily Life of the Immortal King",
                "original_title": "仙王的日常生活",
                "description": "An overpowered immortal king tries to live a normal daily life while hiding his vast power and mysterious background from those around him.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2020,
                "language": ["Chinese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Haoliners Animation League",
                "poster_url": "./The-Daily-Life-of-the-Immortal-King1.jpg",
                "tab_number": 1
            },

            // .......................................................................................................

            {
                "type": "anime",
                "title": "Handa-kun",
                "original_title": "はんだくん",
                "description": "A prequel to Barakamon following Sei Handa, a popular high school calligrapher who misinterprets his classmates' admiration as contempt and thinks he is being bullied.",
                "genres": ["Comedy", "School", "Slice of Life"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2016,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Diomedea",
                "poster_url": "./Handa-Kun.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "We Never Learn: Bokuben",
                "original_title": "ぼくたちは勉強ができない",
                "description": "A talented tutor must help three genius girls excel in their weakest subjects while managing their romantic feelings for him.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Arvo Animation & Silver Co.",
                "poster_url": "./We-Never-Learn-Bokuben.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Friends Game",
                "original_title": "トモダチゲーム",
                "description": "Five friends are dragged into a mysterious psychological game involving friendship and deception when their school trip funds are stolen.",
                "genres": ["Psychological", "Thriller", "Drama"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Okuruto Noboru",
                "poster_url": "./Friends-Game.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "My Wife is the Student Council President",
                "original_title": "おくさまが生徒会長!",
                "description": "A high school vice-president discovers that the student council president is his arranged fiancée after an agreement made by their parents.",
                "genres": ["Comedy", "Romance", "Ecchi"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-MA",
                "studio": "Seven Co., Ltd.",
                "poster_url": "./My-Wife-is-the-Student-Council-President.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Kaguya-sama: Love Is War",
                "original_title": "かぐや様は告らせたい",
                "description": "Two proud geniuses engage in an elaborate psychological battle to make the other confess their love first.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "A-1 Pictures",
                "poster_url": "./Kaguya-sama_Love-Is-War.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "The Way of the Househusband",
                "original_title": "極主夫道",
                "description": "A legendary yakuza boss retires from crime to become a devoted househusband, balancing domestic life with unexpected encounters from his past.",
                "genres": ["Comedy", "Slice of Life", "Drama"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "J.C.Staff",
                "poster_url": "./The-Way-of-the-Househusband.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Wise Man's Grandchild",
                "original_title": "賢者の孫",
                "description": "A young man reborn in a magical world is raised by the legendary sage Merlin and must attend magic academy while lacking common sense.",
                "genres": ["Action", "Fantasy", "Adventure"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Silver Link",
                "poster_url": "./Wise-Man's-Grandchild.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Tower of God",
                "original_title": "神之塔 -Tower of God-",
                "description": "A boy enters a mysterious tower filled with tests and challenges to find his friend Rachel and uncover the tower's secrets.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2020,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Telecom Animation Film",
                "poster_url": "./Tower-of-God.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "That Time I Got Reincarnated as a Slime Season 3",
                "original_title": "転生したらスライムだった件 第3期",
                "description": "Rimuru Tempest, a demon slime, continues building his nation while facing new threats and political conspiracies.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 3,
                "total_seasons": 3,
                "year": 2024,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "8bit",
                "poster_url": "./That-Time-I-Got-Reincarnated-as-a-Slime.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Welcome to Demon School! Iruma-kun",
                "original_title": "悪魔学校のイルマくん",
                "description": "A human boy is sold to a demon and enrolled in demon school where he must hide his identity while making friends.",
                "genres": ["Comedy", "Fantasy", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Bandai Namco Pictures",
                "poster_url": "./Welcome-to-Demon-School!_Iruma-kun.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Mushoku Tensei: Jobless Reincarnation",
                "original_title": "無職転生 ～異世界行ったら本気だす～",
                "description": "A jobless man reincarnates in a fantasy world and becomes determined to live his new life to the fullest without regrets.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Studio Bind",
                "poster_url": "./Mushoku-Tensei_Jobless-Reincarnation.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "Dr. Stone",
                "original_title": "ドクターストーン",
                "description": "After humanity is mysteriously petrified, a genius boy works to rebuild civilization from scratch using science in a stone world.",
                "genres": ["Adventure", "Sci-Fi", "Drama"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "TMS Entertainment",
                "poster_url": "./Dr-Stone.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "The Misfit of Demon King Academy II",
                "original_title": "魔王学院の不適合者 Ⅱ",
                "description": "The overpowered demon king Anos attends an academy where he must navigate conspiracies and reveal his true identity.",
                "genres": ["Action", "Fantasy", "School"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Silver Link",
                "poster_url": "./The-Misfit-of-Demon-King-Academy.jpg",
                "tab_number": 2
            },
            {
                "type": "anime",
                "title": "The Iceblade Sorcerer Shall Rule the World",
                "original_title": "冰剣の魔術師が世界を統べる",
                "description": "A legendary sorcerer enrolls in an elite magic academy under a false identity, seeking an ordinary school life.",
                "genres": ["Action", "Fantasy", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-14",
                "studio": "Cloud Hearts",
                "poster_url": "./The-Iceblade-Sorcerer-Shall-Rule-the-World.jpg",
                "tab_number": 2
            },

            // .....................................................................................................................

            {
                "type": "anime",
                "title": "Oshi no Ko",
                "original_title": "【推しの子】",
                "description": "A murdered doctor is reborn as the child of his favorite idol and grows up inside the dark world of the entertainment industry.",
                "genres": ["Drama", "Mystery", "Supernatural"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Doga Kobo",
                "poster_url": "./Oshi-No-Ko.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Solo Leveling",
                "original_title": "俺だけレベルアップな件",
                "description": "In a world of monster gates and hunters, the weakest hunter gains a unique system that lets him level up without limit.",
                "genres": ["Action", "Fantasy", "Adventure"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 1,
                "year": 2024,
                "language": ["Japanese", "Korean"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "A-1 Pictures",
                "poster_url": "./Solo-Leveling.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Hell's Paradise: Jigokuraku",
                "original_title": "地獄楽",
                "description": "Death-row ninja Gabimaru joins a deadly expedition to a mysterious island to find the elixir of life in exchange for a pardon.",
                "genres": ["Action", "Dark Fantasy", "Historical"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "MAPPA",
                "poster_url": "./Hells-Paradise.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "The Aristocrat's Otherworldly Adventure: Serving Gods Who Go Too Far",
                "original_title": "異世界でチート能力を手にした俺は, 現実世界をも無双する",
                "description": "A boy reincarnated as a noble in another world uses overpowered abilities granted by whimsical gods to live freely and protect those around him.",
                "genres": ["Fantasy", "Adventure", "Comedy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "EMT Squared & Magic Bus",
                "poster_url": "./The-Aristocrat's-Otherworldly-Adventure_Serving-Gods-Who-Go-Too-Far.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Mashle: Magic and Muscles",
                "original_title": "マッシュル-MASHLE-",
                "description": "In a world where magic is everything, a boy with no magic uses overwhelming physical strength to survive at a magic academy.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "A-1 Pictures",
                "poster_url": "./Mashle_Magic-and-Muscles.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Konosuba: God's Blessing on This Wonderful World! 3",
                "original_title": "この素晴らしい世界に祝福を！3",
                "description": "Kazuma and his chaotic party continue their ridiculous adventures in a fantasy world filled with quests, debt and explosions.",
                "genres": ["Comedy", "Fantasy", "Adventure"],
                "status": "completed",
                "season": 3,
                "total_seasons": 3,
                "year": 2024,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Drive",
                "poster_url": "./Konosuba_God's-Blessing-on-This-Wonderful-World.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Rent-a-Girlfriend Season 3",
                "original_title": "彼女、お借りします 第3期",
                "description": "Kazuya’s complicated rental relationships and real feelings escalate as he continues to date rented girlfriends while chasing his dreams.",
                "genres": ["Romance", "Comedy", "Slice of Life"],
                "status": "completed",
                "season": 3,
                "total_seasons": 3,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "TMS Entertainment",
                "poster_url": "./Rent-a-Girlfriend.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Chivalry of a Failed Knight",
                "original_title": "落第騎士の英雄譚",
                "description": "At a school where magic knights duel, an underachieving boy and a top‑ranked princess share a room and aim to become great knights together.",
                "genres": ["Action", "Romance", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Silver Link & Nexus",
                "poster_url": "./Chivalry-of-a-Failed-Knight.jpeg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway",
                "original_title": "ひげを剃る。そして女子高生を拾う。",
                "description": "A salaryman takes in a runaway high school girl, and both slowly confront their past wounds and future choices while living together.",
                "genres": ["Drama", "Romance", "Slice of Life"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Project No.9",
                "poster_url": "./Higehiro_After-Being-Rejected,-I-Shaved-and-Took-in-a-High-School-Runaway.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Fairy Tail",
                "original_title": "フェアリーテイル",
                "description": "Lucy joins the Fairy Tail mage guild and teams up with Natsu and friends for dangerous missions and battles against dark guilds.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2009,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "A-1 Pictures, Satelight, Bridge",
                "poster_url": "./Fairy-Tail-Television-Show.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "The Quintessential Quintuplets",
                "original_title": "五等分の花嫁",
                "description": "A broke top‑student becomes a tutor for identical quintuplet sisters who initially hate studying and him.",
                "genres": ["Romance", "Comedy", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Tezuka Productions",
                "poster_url": "./The-Quintessential-Quintuplets.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "In Another World With My Smartphone",
                "original_title": "異世界はスマートフォンとともに。",
                "description": "After dying from a mistake, a boy is revived in a fantasy world with his smartphone and powerful blessings from God.",
                "genres": ["Fantasy", "Adventure", "Harem"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Production Reed",
                "poster_url": "./In-Another-World-With-My-Smartphone.jpg",
                "tab_number": 3
            },
            {
                "type": "anime",
                "title": "Arifureta: From Commonplace to World's Strongest",
                "original_title": "ありふれた職業で世界最強",
                "description": "A bullied boy falls into an abyss during a class isekai, survives by changing himself, and returns as an overpowered anti‑hero.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Asread & White Fox",
                "poster_url": "./Arifureta_From-Commonplace-to-World's-Strongest.jpg",
                "tab_number": 3
            },

            //.................................................................................................


            {
                "type": "anime",
                "title": "Sword Art Online: Alicization - War of Underworld",
                "original_title": "ソードアート・オンライン アリシゼーション War of Underworld",
                "description": "Kirito awakens from his coma to join the final battle in the Underworld as human players enter the war against the forces of darkness.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 3,
                "total_seasons": 4,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "A-1 Pictures",
                "poster_url": "./Sword-Art-Online.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Food Wars! Shokugeki no Soma",
                "original_title": "食戟のソーマ",
                "description": "Soma enrolls in an elite culinary academy where students battle in high-stakes cooking competitions called Shokugeki.",
                "genres": ["Comedy", "School", "Slice of Life"],
                "status": "completed",
                "season": 1,
                "total_seasons": 5,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "J.C.Staff",
                "poster_url": "./Food-Wars.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "A Galaxy Next Door",
                "original_title": "星降る夜に君想ふ",
                "description": "A manga artist struggling to make ends meet finds himself living with his new assistant and her mysterious little sister.",
                "genres": ["Romance", "Drama", "Slice of Life"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Studio Gokumi",
                "poster_url": "./A-Galaxy-Next-Door.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "A Couple of Cuckoos",
                "original_title": "カッコウの許嫁",
                "description": "Two babies were switched at birth. Now high schoolers, they're forced into an arranged marriage by their families.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Shin-Ei Animation",
                "poster_url": "./A-Couple-of-Cuckoos.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Kubo Won't Let Me Be Invisible",
                "original_title": "久保さんは僕を許さない",
                "description": "A boy who is constantly overlooked discovers that his classmate Kubo can always see him, leading to sweet everyday moments.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Pine Jam",
                "poster_url": "./Kubo-Won't-Let-Me-Be-Invisible.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "86 -Eighty Six-",
                "original_title": "86-エイティシックス-",
                "description": "In a dystopian future, the Republic fights a war with drones operated by the oppressed 86th district's children.",
                "genres": ["Action", "Drama", "Mecha"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "A-1 Pictures",
                "poster_url": "./86-Eighty-Six.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "TONIKAWA: Over the Moon For You",
                "original_title": "TONIKAWA：過度な月愛",
                "description": "A young man proposes to a girl he just met, and they get married the same day, exploring newlywed life together.",
                "genres": ["Comedy", "Romance", "Slice of Life"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2020,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Seven Arcs",
                "poster_url": "./TONIKAWA_Over-the-Moon-For-You.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Horimiya",
                "original_title": "ホリミヤ",
                "description": "A popular girl and a gloomy boy discover each other's true selves and develop a deep, genuine relationship.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "CloverWorks",
                "poster_url": "./Horimiya.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Tomo-chan Is a Girl!",
                "original_title": "トモちゃんは女の子！",
                "description": "Tomo has been best friends with Jun for years but struggles to get him to see her as a romantic interest despite her tomboy personality.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Lay-duce",
                "poster_url": "./Tomo-Chan-Is-a-Girl.png",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "My Stepsister is My Ex-Girlfriend",
                "original_title": "お兄ちゃんはおしまい！",
                "description": "A boy discovers his new stepsister is his ex-girlfriend from middle school, forcing them to navigate their awkward new family dynamic.",
                "genres": ["Comedy", "Romance", "Slice of Life"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Studio Silver",
                "poster_url": "./My-Stepsister-is-My-Ex-Girlfriend.png",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "The Saint's Magic Power is Omnipotent Season 2",
                "original_title": "聖女の魔力は万能です",
                "description": "Sei continues her peaceful life in a fantasy world, using her magical herbal knowledge to help people while avoiding political intrigue.",
                "genres": ["Fantasy", "Romance", "Isekai"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Diomedéa",
                "poster_url": "./The-Saint's-Magic-Power-is-Omnipotent.png",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Re:Zero - Starting Life in Another World",
                "original_title": "Re:ゼロから始める異世界生活",
                "description": "Subaru is transported to a fantasy world where he discovers he can return from death by experiencing loops of suffering and sacrifice.",
                "genres": ["Action", "Drama", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 3,
                "year": 2016,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "White Fox",
                "poster_url": "./Re_Zero-Starting-Life-in-Another-World.webp",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "ORESUKI: Are You the Only One Who Loves Me?",
                "original_title": "Ore wo Suki nano wa Omae dake ka yo",
                "description": "A boy navigates a complex love triangle where both girls claim to love him, but their true motives reveal unexpected twists.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Connect",
                "poster_url": "./ORESUKI_Are-You-the-Only-One-Who-Loves-Me.png",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Knight's & Magic",
                "original_title": "ナイツ&マジック",
                "description": "A mecha otaku reincarnates in a fantasy world and uses his engineering knowledge to build the ultimate magical robots.",
                "genres": ["Action", "Adventure", "Mecha"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "8bit",
                "poster_url": "./Knight's-&-Magic.jpe",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Ascendance of a Bookworm",
                "original_title": "本好きの下剋上",
                "description": "A book-loving girl reincarnates in a world without paper and dedicates her new life to inventing books and spreading literacy.",
                "genres": ["Fantasy", "Slice of Life", "Isekai"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 3,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "AJIADO",
                "poster_url": "./Ascendance-of-a-Bookworm.png",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Tsukimichi: Moonlit Fantasy",
                "original_title": "月が導く異世界道中",
                "description": "A boy summoned as a hero is rejected by the goddess and banished to the world's edge, where he builds his own monster-filled community.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "C2C",
                "poster_url": "./Tsukimichi_Moonlit-Fantasy.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Banished from the Hero's Party",
                "original_title": "勇者パーティーを追放されたビーストテイマー、最強種の猫耳少女と出会う。",
                "description": "A support class adventurer is banished from the hero's party and starts a new life with a powerful beast tamer girl.",
                "genres": ["Adventure", "Fantasy", "Romance"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Studio Flad",
                "poster_url": "./Banished-from-the-Hero's-Party.jpg",
                "tab_number": 4
            },
            {
                "type": "anime",
                "title": "Skeleton Knight in Another World",
                "original_title": "骸骨騎士様、只で異世界を楽しむ",
                "description": "A gamer wakes up as his overpowered skeleton avatar in a fantasy world and goes on comedic adventures while hiding his true appearance.",
                "genres": ["Action", "Adventure", "Comedy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Studio Kai",
                "poster_url": "./Skeleton-Knight-in-Another-World.png",
                "tab_number": 4
            },

            // .........................................................................................................


            {
                "type": "anime",
                "title": "The Strongest Sage with the Weakest Crest",
                "original_title": "失格紋の最強賢者",
                "description": "The greatest sage reincarnates into a new life with a flawed magic crest but uses his vast knowledge to become the strongest once again.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "J.C.Staff",
                "poster_url": "./The-Strongest-Sage-with-the-Weakest-Crest.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "The Greatest Demon Lord Is Reborn as a Typical Nobody",
                "original_title": "史上最強の大魔王、転生して林下の下僕になる",
                "description": "The world's strongest demon lord reincarnates as an ordinary student but retains all his overwhelming power.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Silver Link",
                "poster_url": "./The-Greatest-Demon-Lord-Is-Reborn-as-a-Typical-Nobody.jpeg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Handyman Saitou in Another World",
                "original_title": "手品師さいとう在異世界",
                "description": "A handyman joins adventurers in a fantasy world where his everyday skills prove surprisingly useful in dangerous situations.",
                "genres": ["Adventure", "Comedy", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Studio Flad",
                "poster_url": "./Handyman-Saitou-in-Another-World.jpeg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Summoned to Another World for a Second Time",
                "original_title": "二度召喚されて異世界を征服する",
                "description": "A man summoned to another world returns home but gets pulled back for a second adventure with even greater power.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Studio Hokiboshi",
                "poster_url": "./Summoned-to-Another-World-for-a-Second-Time.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Lord Marksman and Vanadis",
                "original_title": "魔装学園H×H",
                "description": "A skilled archer becomes entangled with warlords wielding magical weapons in a medieval fantasy war.",
                "genres": ["Action", "Adventure", "Ecchi"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2014,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Twinkle",
                "poster_url": "./Lord-Marksman-and-Vanadis.jpg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Monster Musume: Everyday Life with Monster Girls",
                "original_title": "モンスター娘のいる日常",
                "description": "A young man becomes host to various monster girls living together under an interspecies cultural exchange program.",
                "genres": ["Comedy", "Ecchi", "Harem"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "TV-MA",
                "studio": "Lerche",
                "poster_url": "./Monster-Musume-Everyday-Life-with-Monster-Girls.jpg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Farming Life in Another World",
                "original_title": "異世界田舎生活",
                "description": "A salaryman reincarnates in a fantasy world and uses modern farming techniques to build a peaceful agricultural life.",
                "genres": ["Fantasy", "Slice of Life", "Isekai"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Zero-G",
                "poster_url": "./Farming-Life-in-Another-World.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Spirit Chronicles",
                "original_title": "精霊幻想記",
                "description": "A pharmacist summoned to another world forms contracts with powerful spirits and builds a new life with his magical abilities.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Troyca",
                "poster_url": "./Spirit-Chronicles.jpg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
                "original_title": "世界最高の暗殺者、異世界貴族に転生する",
                "description": "The greatest assassin is reincarnated by god with a mission to kill the hero using his unmatched killing skills in a new world.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Silver Link & Studio Palette",
                "poster_url": "./The-World's-Finest-Assassin-Gets-Reincarnated-in-Another-World-as-an-Aristocrat.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "I Got a Cheat Skill in Another World and Became Unrivaled in the Real World, Too",
                "original_title": "異世界でチート能力を手にした俺は、現実世界でも無双する",
                "description": "A bullied boy discovers a portal to another world where he gains cheat powers that also enhance his real-world life.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Millepensee",
                "poster_url": "./I-Got-a-Cheat-Skill-in-Another-World-and-Became-Unrivaled-in-the-Real-World,Too.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Dead Mount Death Play",
                "original_title": "デッドマウント・デスプレイ",
                "description": "A necromancer from another world possesses a corpse in modern Japan and battles mysterious forces while uncovering his past.",
                "genres": ["Action", "Supernatural", "Seinen"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Geek Toys",
                "poster_url": "./Dead-Mount-Death-Play.jpg",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Komi Can't Communicate",
                "original_title": "古見さんは、コミュ症です。",
                "description": "A beautiful but socially anxious girl aims to make 100 friends with the help of her classmate who understands her struggles.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2021,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Olm",
                "poster_url": "./Komi-Can't-Communicate.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "The Dangers in My Heart",
                "original_title": "僕の心のヤバイやつ",
                "description": "A gloomy middle school boy with dark fantasies develops feelings for the cheerful, popular girl in his class.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Atelier Pont d'Arc",
                "poster_url": "./The-Dangers-in-My-Heart.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Masamune-kun's Revenge",
                "original_title": "政宗くんのリベンジ！",
                "description": "A boy returns after years of training to exact revenge on the rich girl who rejected and humiliated him in elementary school.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Silver Link",
                "poster_url": "./Masamune-kun's-Revenge.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "The Fruit of Evolution: Before I Knew It, My Life Had It Made.",
                "original_title": "進化の実～知らないうちに勝ち組人生～",
                "description": "Hiraku continues building his ideal utopian village with monster girls after being reincarnated with evolution powers.",
                "genres": ["Comedy", "Fantasy", "Harem"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "HOTLINE",
                "poster_url": "./The-Fruit-of-Evolution-Before-I-Knew-It_My-Life-Had-It-Made.png",
                "tab_number": 5
            },
            {
                "type": "anime",
                "title": "Trapped in a Dating Sim: The World of Otome Games is Tough for Mobs",
                "original_title": "乙女ゲー世界はモブに厳しい世界です",
                "description": "A student reincarnates into an otome game as a background character and uses game knowledge to survive the harsh noble society.",
                "genres": ["Comedy", "Mecha", "Isekai"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 1,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Swordfish",
                "poster_url": "./Trapped-in-a-Dating-Sim_The-World-of-Otome-Games-is-Tough-for-Mobs.png",
                "tab_number": 5
            }


        ]
    },
    reducers: {
        message: (state, { payload }) => {
            console.log("hi");
        }
    }
})

export const { message } = listSlice.actions
export default listSlice.reducer


