import { createSlice } from "@reduxjs/toolkit";

const listSlice = createSlice({
    name: "List",
    initialState: {
        list: [
            {
                "type": "anime",
                "title": "Bleach: Thousand-Year Blood War - The Separation",
                "original_title": "BLEACH 千年血戦篇-訣別譚-",
                "description": "Ichigo and the Soul Reapers continue their intense battle against Yhwach and the Quincy invasion as the fate of both worlds hangs in the balance.",
                "genres": ["Action", "Supernatural", "Fantasy"],
                "status": "completed",
                "season": 2,
                "total_seasons": 4,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Pierrot",
                "poster_url": "https://example.com/bleach-tybw-separation.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Jujutsu Kaisen Season 2",
                "original_title": "呪術廻戦 第2期",
                "description": "Gojo's past unfolds while the Shibuya Incident reveals the true threat of Jujutsu Society as powerful curses wreak havoc on Tokyo.",
                "genres": ["Action", "Dark Fantasy", "Supernatural"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "MAPPA",
                "poster_url": "https://example.com/jujutsu-kaisen-s2.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Classroom of the Elite",
                "original_title": "ようこそ実力至上主義の教室へ",
                "description": "In an elite government school, students compete ruthlessly through exams and psychological games with their futures at stake.",
                "genres": ["Psychological", "Drama", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Lerche",
                "poster_url": "https://example.com/classroom-of-the-elite.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "One Punch Man",
                "original_title": "ワンパンマン",
                "description": "Saitama, an overpowered hero who defeats enemies with a single punch, searches for a worthy opponent to rekindle his passion for battle.",
                "genres": ["Action", "Comedy", "Superhero"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2015,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Madhouse",
                "poster_url": "https://example.com/one-punch-man.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Mob Psycho 100 III",
                "original_title": "モブサイコ 100 III",
                "description": "Mob, a middle school psychic, continues to control his overwhelming powers while navigating friendships, school, and personal growth.",
                "genres": ["Action", "Comedy", "Supernatural"],
                "status": "completed",
                "season": 3,
                "total_seasons": 3,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Bones",
                "poster_url": "https://example.com/mob-psycho-100-iii.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Demon Slayer: Kimetsu no Yaiba - Hashira Training Arc",
                "original_title": "鬼滅の刃 柱稽古編",
                "description": "Tanjiro undergoes intense training with the Hashira to prepare for his final confrontation with Muzan Kibutsuji.",
                "genres": ["Action", "Dark Fantasy", "Supernatural"],
                "status": "completed",
                "season": 4,
                "total_seasons": 4,
                "year": 2024,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Ufotable",
                "poster_url": "https://example.com/demon-slayer-hashira.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Spy x Family Season 2",
                "original_title": "SPY×FAMILY シーズン2",
                "description": "The Forger family continues their secret missions while maintaining the facade of a perfect family under constant danger and scrutiny.",
                "genres": ["Action", "Comedy", "Slice of Life"],
                "status": "completed",
                "season": 2,
                "total_seasons": 2,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Wit Studio & Cloverworks",
                "poster_url": "https://example.com/spy-x-family-s2.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Death Note",
                "original_title": "デスノート",
                "description": "A student discovers a supernatural notebook that kills anyone whose name is written in it, leading to a battle of wits with a mysterious detective.",
                "genres": ["Psychological", "Thriller", "Supernatural"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2006,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "R-17",
                "studio": "Madhouse",
                "poster_url": "https://example.com/death-note.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Black Clover",
                "original_title": "ブラッククローバー",
                "description": "Aster, a powerless boy in a world of mages, joins the Black Bull squad and strives to become the Wizard King through sheer determination and effort.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 5,
                "year": 2017,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Pierrot",
                "poster_url": "https://example.com/black-clover.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Eminence in Shadow",
                "original_title": "陰の実力者になりたくて",
                "description": "Cid Kagenou, a reborn otaku, manipulates events from the shadows as the mysterious Shadow while building his secret organization.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "ongoing",
                "season": 1,
                "total_seasons": 2,
                "year": 2022,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Nexus",
                "poster_url": "https://example.com/eminence-in-shadow.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Reincarnation of the Strongest Exorcist in Another World",
                "original_title": "最強陰陽師の異世界転生記",
                "description": "A powerful exorcist is reincarnated in a fantasy world where he uses his spiritual powers to become the strongest warrior.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2023,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "J.C.Staff",
                "poster_url": "https://example.com/exorcist-reincarnation.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Fire Force",
                "original_title": "炎炎ノ消防隊",
                "description": "Shinra Kusakabe joins a special firefighting force to combat spontaneous human combustion while uncovering the truth behind supernatural flames.",
                "genres": ["Action", "Adventure", "Supernatural"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2019,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "David Production",
                "poster_url": "https://example.com/fire-force.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "Hunter x Hunter",
                "original_title": "ハンターハンター",
                "description": "Gon seeks to become a Hunter like his father, embarking on an epic adventure filled with dangerous challenges, friendships, and dark conspiracies.",
                "genres": ["Action", "Adventure", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 2,
                "year": 2011,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Madhouse",
                "poster_url": "https://example.com/hunter-x-hunter.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "My Teen Romantic Comedy SNAFU",
                "original_title": "やはり俺の青春ラブコメはまちがっている。",
                "description": "An introverted student joins a school club where he and two others solve student problems with unconventional methods and hidden romance.",
                "genres": ["Comedy", "Romance", "School"],
                "status": "completed",
                "season": 1,
                "total_seasons": 3,
                "year": 2013,
                "language": ["Japanese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Brain's Base",
                "poster_url": "https://example.com/snafu.jpg",
                "tab_number": 1
            },
            {
                "type": "anime",
                "title": "The Daily Life of the Immortal King",
                "original_title": "仙王的日常生活",
                "description": "An overpowered immortal king tries to live a normal daily life while hiding his vast power and mysterious background from those around him.",
                "genres": ["Action", "Comedy", "Fantasy"],
                "status": "completed",
                "season": 1,
                "total_seasons": 1,
                "year": 2020,
                "language": ["Chinese", "English"],
                "subtitles": ["English", "Hindi"],
                "age_rating": "PG-13",
                "studio": "Haoliners Animation League",
                "poster_url": "https://example.com/immortal-king.jpg",
                "tab_number": 1
            }
        ]

    }
})